name: pytest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, '3.10', 3.11, 3.12]
        sklearn: [1.0.2, 1.1.3, 1.2.2, 1.3.2, 1.4.2, 1.5.2, 1.6.1, 1.7.2]
        exclude:
          - python: 3.8
            sklearn: 1.4.2
          - python: 3.8
            sklearn: 1.5.2
          - python: 3.8
            sklearn: 1.6.1
          - python: 3.8
            sklearn: 1.7.2
          - python: 3.9
            sklearn: 1.7.2
          - python: 3.11
            sklearn: 1.0.2
          - python: 3.12
            sklearn: 1.0.2
          - python: 3.12
            sklearn: 1.1.3
          - python: 3.12
            sklearn: 1.2.2

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --only-binary :all: scikit-learn==${{ matrix.sklearn }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: |
        python -m pytest
